export const RENKLER = {
  bg: '#0a1f15',
  bg2: '#123322',
  bg3: '#1a4530',
  metin: '#f3f7f3',
  metinIkincil: '#c3d6c9',
  metinUcuncul: '#82a08d',
  ayrici: '#255339',
  vurgu: '#ff8a1e',
  vurgu2: '#ffcf5c',
  basari: '#3ecf8e',
  hata: '#ff6b5c',
  uyari: '#ffcf5c',
};

export const ORTAK_STIL = {
  ekran: { flex: 1, backgroundColor: RENKLER.bg },
  kart: {
    backgroundColor: RENKLER.bg2,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: RENKLER.ayrici,
    borderLeftWidth: 3,
    borderLeftColor: RENKLER.vurgu,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  buyukButon: {
    backgroundColor: RENKLER.vurgu,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: RENKLER.vurgu,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 4,
  },
};
